# Generated by Django 5.1.5 on 2025-03-03 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal_accounts', '0005_alter_personalaccount_flat_and_more'),
        ('system_settings', '0007_alter_tariffservice_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_complete', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_transactions', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_transactions', to=settings.AUTH_USER_MODEL)),
                ('payment_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='system_settings.paymentitem')),
                ('personal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_transactions', to='personal_accounts.personalaccount')),
            ],
        ),
    ]
