# Generated by Django 5.1.5 on 2025-03-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_box', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'надходження'), ('expense', 'витрата')], default='expense'),
        ),
    ]
