# Generated by Django 5.1.5 on 2025-03-04 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_box', '0003_alter_transaction_amount'),
        ('payment_receipts', '0004_alter_receiptservice_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_receipts.receipt'),
        ),
    ]
