services:
  web:
    build:
      dockerfile: ./deploy/web/Dockerfile
    container_name: django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app:rw
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./deploy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis

  celery:
    build:
      context: .
      dockerfile: ./deploy/celery/Dockerfile
    command: celery -A config worker -l info
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  pgdata:
  static_volume:
  media_volume: