from .houses import AdminPersonalAccountHousesView
from .sections import AdminPersonalAccountSectionsView
from .flats import AdminPersonalAccountFlatsView
from .owner import AdminPersonalAccountOwnerView
from .owners import AdminPersonalAccountOwnersView