# Generated by Django 5.1 on 2024-10-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        ('houses', '0004_alter_housefloor_house_alter_housesection_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('active', 'активний'), ('disabled', 'деактивований')], default='active')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.flat')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.housesection')),
            ],
        ),
    ]
