# Generated by Django 5.1 on 2024-10-16 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_remove_flat_personal_account_alter_flat_owner'),
        ('personal_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flats.flat'),
        ),
    ]
