# Generated by Django 5.1 on 2024-10-29 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_alter_housefloor_house_alter_housesection_house'),
        ('personal_accounts', '0003_alter_personalaccount_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.house'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.housesection'),
        ),
    ]
