# Generated by Django 5.1.5 on 2025-02-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0007_alter_flat_tariff'),
        ('houses', '0006_alter_houseuser_user'),
        ('personal_accounts', '0004_alter_personalaccount_house_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='flat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flats.flat'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.house'),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='houses.housesection'),
        ),
    ]
