# Generated by Django 5.1.5 on 2025-02-22 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0007_alter_flat_tariff'),
        ('houses', '0006_alter_houseuser_user'),
        ('personal_accounts', '0004_alter_personalaccount_house_and_more'),
        ('system_settings', '0007_alter_tariffservice_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('is_complete', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('paid', 'оплачена'), ('partially_paid', 'частково оплачена'), ('unpaid', 'неоплачена')], default='unpaid')),
                ('period_from', models.DateField()),
                ('period_to', models.DateField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.flat')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('personal_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personal_accounts.personalaccount')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.housesection')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.tariff')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=1, max_digits=6)),
                ('value', models.FloatField()),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_receipts.receipt')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.service')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.measurementunit')),
            ],
        ),
    ]
