# Generated by Django 5.1.5 on 2025-02-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_receipts', '0001_initial'),
        ('personal_accounts', '0005_alter_personalaccount_flat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='owner',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='personal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal_accounts.personalaccount'),
        ),
    ]
