# Generated by Django 5.1.5 on 2025-02-27 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter_indicators', '0002_rename_countermeasurement_meterindicator'),
        ('payment_receipts', '0002_remove_receipt_owner_alter_receipt_personal_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptservice',
            name='meter_indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meter_indicators.meterindicator'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='status',
            field=models.CharField(choices=[('unpaid', 'неоплачена'), ('partially_paid', 'частково оплачена'), ('paid', 'оплачена')], default='unpaid'),
        ),
    ]
