# Generated by Django 5.1.5 on 2025-03-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_receipts', '0003_receiptservice_meter_indicator_alter_receipt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptservice',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='payment_receipts.receipt'),
        ),
    ]
