# Generated by Django 5.1.5 on 2025-03-11 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_receipts', '0004_alter_receiptservice_receipt'),
        ('personal_accounts', '0005_alter_personalaccount_flat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='personal_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_receipts', to='personal_accounts.personalaccount'),
        ),
    ]
