# Generated by Django 5.1.5 on 2025-03-23 16:38

import src.core.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_receipts', '0009_alter_receiptservice_meter_indicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('file', models.FileField(upload_to=src.core.utils.media.get_upload_path)),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
    ]
