from .api import *
from .create import AdminReceiptsCreateView
from .update import AdminReceiptsUpdateView
from .list import AdminReceiptsListView
from .datatable import AdminReceiptsDatatableView
from .delete_many import AdminReceiptsDeleteManyView
from .delete import AdminReceiptsDeleteView
from .detail import AdminReceiptDetailView
from .template_settings import AdminReceiptsTemplateSettingsView