# Generated by Django 5.1 on 2024-09-13 18:09

import src.core.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField()),
                ('seo_keywords', models.CharField()),
                ('seo_description', models.TextField()),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('show_app_links', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainPageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=src.core.utils.media.get_upload_path)),
                ('title', models.CharField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPageSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=src.core.utils.media.get_upload_path)),
            ],
        ),
    ]
