# Generated by Django 5.1 on 2024-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='show_app_links',
            field=models.BooleanField(default=False),
        ),
    ]
