# Generated by Django 5.1 on 2024-09-17 16:00

import src.core.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_management', '0002_alter_mainpage_show_app_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsAdditionalGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=src.core.utils.media.get_upload_path)),
            ],
        ),
        # migrations.CreateModel(
        #     name='ABoutUsDocument',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('file', models.FileField(upload_to=src.core.utils.media.get_upload_path)),
        #     ],
        # ),
        migrations.CreateModel(
            name='AboutUsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=src.core.utils.media.get_upload_path)),
            ],
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField()),
                ('seo_keywords', models.CharField()),
                ('seo_description', models.TextField()),
                ('director_photo', models.ImageField(upload_to=src.core.utils.media.get_upload_path)),
                ('title', models.CharField()),
                ('description', models.TextField()),
                ('additional_title', models.CharField()),
                ('additional_description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
