from .delete import AdminReceiptTemplatesDeleteView
from .settings import AdminReceiptsTemplateSettingsView
from .set_default import AdminReceiptsTemplateSetDefaultView
from .print import AdminReceiptPrintView