# Generated by Django 5.1 on 2024-12-03 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0005_flat_floor'),
        ('houses', '0004_alter_housefloor_house_alter_housesection_house'),
        ('system_settings', '0006_alter_tariffservice_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('new', 'Нове'), ('accounted', 'Враховано'), ('accounted_paid', 'Враховано та оплачено'), ('zero', 'Нульове')], default='new', max_length=20)),
                ('value', models.FloatField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flats.flat')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.house')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.housesection')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.service')),
            ],
        ),
    ]
