# Generated by Django 5.1 on 2024-12-03 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0005_flat_floor'),
        ('houses', '0004_alter_housefloor_house_alter_housesection_house'),
        ('meter_indicators', '0001_initial'),
        ('system_settings', '0006_alter_tariffservice_tariff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CounterMeasurement',
            new_name='MeterIndicator',
        ),
    ]
