# Generated by Django 5.1.4 on 2025-01-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0006_alter_tariffservice_tariff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffservice',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
