# Generated by Django 5.1 on 2024-08-31 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(choices=[('new', 'новий'), ('active', 'активний'), ('disabled', 'деактивований')], max_length=10),
        ),
    ]
