# Generated by Django 5.1 on 2024-10-16 11:48

import src.core.utils.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=src.core.utils.media.get_upload_path),
        ),
    ]
