# Generated by Django 5.1.4 on 2025-01-04 08:37

import src.authentication.models.custom_user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=src.authentication.models.custom_user.upload_to),
        ),
    ]
