# Generated by Django 5.1 on 2024-10-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flats', '0001_initial'),
        ('houses', '0004_alter_housefloor_house_alter_housesection_house'),
        ('personal_accounts', '0001_initial'),
        ('system_settings', '0006_alter_tariffservice_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='personal_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_flat', to='personal_accounts.personalaccount'),
        ),
        migrations.AddField(
            model_name='flat',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.housesection'),
        ),
        migrations.AddField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system_settings.tariff'),
        ),
    ]
