# Generated by Django 5.1 on 2024-10-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='square',
            new_name='area',
        ),
    ]
