# Generated by Django 5.1 on 2024-10-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0004_remove_flat_personal_account_alter_flat_owner'),
        ('houses', '0004_alter_housefloor_house_alter_housesection_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='floor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='houses.housefloor'),
            preserve_default=False,
        ),
    ]
