# Generated by Django 5.1.5 on 2025-02-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flats', '0006_alter_flat_owner'),
        ('system_settings', '0007_alter_tariffservice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_settings.tariff'),
        ),
    ]
