# Generated by Django 5.1.4 on 2024-12-21 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('master_call_requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastercallrequest',
            name='master_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
