# Generated by Django 5.1.5 on 2025-03-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0006_alter_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlatOwner',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.customuser',),
        ),
    ]
